### ISSUE TITLE
[BUG] tilt_shift.py ZeroDivisionError

### ISSUE THREAD

**Issue by yassinebebba** [L3str4nge/imgprocalgs#11]
# Information about the issue

sharpen_area_size is optional and defaults to [0, 0] which will later on be used in:

```
def _make_blur(self, distance: int, sharp_area_size: int):
    """
    :param distance: distance between point and sharp area
    :param sharp_area_size: sharp area size height/width
    :return: blur value
    """
    return abs(self.min_blur + (self.max_blur - self.min_blur) * distance / sharp_area_size)
```
the devision by sharp_area_size will always be zero if the 2 numbers in the list are the same because it is calculated like this:

```
self.sharpen_min_h, self.sharpen_max_h = sharpen_area_size[0], sharpen_area_size[1]
self.sharpen_size = self.sharpen_max_h - self.sharpen_min_h
```
# More information about the Error

```
Traceback (most recent call last):
  File "/home/sgb/PycharmProjects/imgprocalgs/venv/bin/imgprocalgs-tiltshift", line 33, in <module>
    sys.exit(load_entry_point('imgprocalgs==0.1', 'console_scripts', 'imgprocalgs-tiltshift')())
  File "/home/sgb/PycharmProjects/imgprocalgs/venv/lib64/python3.9/site-packages/imgprocalgs/algorithms/tilt_shift.py", line 129, in main
    TiltShift(
  File "/home/sgb/PycharmProjects/imgprocalgs/venv/lib64/python3.9/site-packages/imgprocalgs/algorithms/tilt_shift.py", line 74, in process
    blur = self._make_blur(self.sharpen_center - y, self.sharpen_size)
  File "/home/sgb/PycharmProjects/imgprocalgs/venv/lib64/python3.9/site-packages/imgprocalgs/algorithms/tilt_shift.py", line 51, in _make_blur
    return abs(self.min_blur + (self.max_blur - self.min_blur) * distance / sharp_area_size)
ZeroDivisionError: float division by zero

```

**Comment by deveshpandee** [comment]
Hey, I am new in open source and I would like to work on this issue. I have understood the problem. Can you please suggest me solution I need to implement.

**Comment by yassinebebba** [comment]
been a long time since i looked at the issue, but i think it's down to the matrix size or something!!!

**Comment by aman11012003** [comment]
hii  @yassinebebba  i am new here and i can't understand the exact issue can u plz  explain little bit about your issue may be i can help you in  this after explanation
